const restaurantCategories = [
    'Burger',
    'Pizza',
    'Rice',
    'Grill',
    'Pasta',
    'Seafood',
    'Salad',
    'Sandwich',
    'Soup',
    'Sushi',
    'Tacos',
    'Breakfast',
    'Dessert',
    'Vegetarian',
    'Vegan',
    'Gluten-Free',
    'Mexican',
    'Chinese',
    'Italian',
    'Indian',
    'Japanese',
    'Mediterranean',
    'BBQ',
    'Steak',
    'Wrap',
    'Smoothie',
    'Coffee',
    'Tea',
    'Cocktail',
    // Add more categories as needed
  ];
  
  export default restaurantCategories;
  